In [1]:
# External Imports
import os
import glob
import os.path
import json
import pandas as pd
import geopandas as gpd
from CoastSeg import bbox

In [ ]:
zenodo_id_mapping={
                    'E_USA_SouthCarolina_NorthCarolina_ref_shoreline.geojson':6824465,
                    'NE_USA_Delaware_Maine_ref_shoreline.geojson':6824429,
                    'SE_USA_Louisiana_Georgia_ref_shoreline.geojson':6824473,
                    'S_USA_Texas_Louisiana_ref_shoreline.geojson':6824487,
                    'W_USA_California_ref_shoreline.geojson':6824504,
                    'W_USA_Oregon_Washington_ref_shoreline.geojson':6824510,}

In [13]:
os.path.splitext('E_USA_SouthCarolina_NorthCarolina_ref_shoreline.geojson')[0]

'E_USA_SouthCarolina_NorthCarolina_ref_shoreline'

In [4]:
shorelines_folder=os.path.abspath(os.getcwd())+os.sep+"Coastseg"+os.sep+"shorelines"
shorelines=glob.glob(shorelines_folder+os.sep+"*.geojson")
shorelines

['c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\E_USA_SouthCarolina_NorthCarolina_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\NE_USA_Delaware_Maine_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\SE_USA_Louisiana_Georgia_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\shoreline_data_Mexico.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\S_USA_Texas_Louisiana_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\USA_Alaska_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\W_USA_California_ref_shoreline.geojson',
 'c:\\1_USGS\\CoastSeg\\repos\\2_CoastSeg\\CoastSeg_fork\\Seg2Map\\Coastseg\\shorelines\\W_USA_Oregon_Washington_ref_shoreline.geojson']

In [5]:
# Loads the geojson from a transects file
with open(shorelines[1]) as f:
    data = json.load(f)
data

{'type': 'FeatureCollection',
 'crs': {'type': 'name',
  'properties': {'name': 'urn:ogc:def:crs:OGC:1.3:CRS84'}},
 'features': [{'type': 'Feature',
   'properties': {'OBJECTID': 3264034,
    'MasterKey': 3264034,
    'RandomSort': 1616964.3464954,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.505744,
    'CHLOROPHYLL': 2.556093,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 1.011592,
    'GHM': 0.710552,
    'MAX_SLOPE': 8.057293,
    'OUTFLOW_DENSITY': 86378.859375,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 782.0044903215424,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'straight',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, straight, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 19760,
    'OUTFLOW_DENSITY_RESCALED': 0.0001044389103175128,
    'Shape_Length': 0.007246014113617252},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.06368720599994, 38.382142663000025],
     [-75.06386653199996, 38.38161106300004],
     [-75.06395155099995, 38.381210993000025],
     [-75.06396197699996, 38.38114057000007],
     [-75.06397545999994, 38.381073204000074],
     [-75.06399381399996, 38.381010709000066],
     [-75.06401920399998, 38.380955251000046],
     [-75.06423846499996, 38.38052002500007],
     [-75.06450941799994, 38.379982494000046],
     [-75.06458625799996, 38.37983796200007],
     [-75.06472714699999, 38.379622734000066],
     [-75.06491902799996, 38.37922750400003],
     [-75.06500410499996, 38.37900266100007],
     [-75.06523933599993, 38.37832546100003],
     [-75.06525640799998, 38.378265534000036],
     [-75.06526851499996, 38.378200641000035],
     [-75.06527702399995, 38.378132153000024],
     [-75.06528305499995, 38.378061185000035],
     [-75.06529947899998, 38.377769615000034],
     [-75.06530550999997, 38.377698648000035],
     [-75.06531402099995, 38.37763016000008],
     [-75.06532612599995, 38.37756526900006],
     [-75.06534319899998, 38.377505341000074],
     [-75.06557847499994, 38.37682818700006],
     [-75.06566362199999, 38.376603414000044],
     [-75.06585598299995, 38.37620866300006],
     [-75.06590611536116, 38.37611542403604]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3264035,
    'MasterKey': 3264035,
    'RandomSort': 2221402.38462139,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.505744,
    'CHLOROPHYLL': 2.48242,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 1.011592,
    'GHM': 0.710552,
    'MAX_SLOPE': 8.237894,
    'OUTFLOW_DENSITY': 86378.859375,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 781.8661135957215,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'straight',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, straight, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 19760,
    'OUTFLOW_DENSITY_RESCALED': 0.0001044389103175128,
    'Shape_Length': 0.007201250320569709},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.06151600399994, 38.388916692000066],
     [-75.06151974499994, 38.388712439000074],
     [-75.06152534899996, 38.38855951600004],
     [-75.06153071499995, 38.38848561900005],
     [-75.06153887099998, 38.38841451300004],
     [-75.06155091499994, 38.38834729400003],
     [-75.06156825099998, 38.38828536700004],
     [-75.06180569299994, 38.387608112000066],
     [-75.06189142199997, 38.387383922000026],
     [-75.06203106899994, 38.38716745200003],
     [-75.06225189699995, 38.38673379200003],
     [-75.06227591599998, 38.386680812000066],
     [-75.06229311299995, 38.386621012000035],
     [-75.06230524499995, 38.38655614500004],
     [-75.06231371799998, 38.386487620000025],
     [-75.06231967899998, 38.38641658200004],
     [-75.06233577399996, 38.38612468400004],
     [-75.06234174999997, 38.38605366100006],
     [-75.06235022299995, 38.385985137000034],
     [-75.06236231099996, 38.38592022300003],
     [-75.06237938399994, 38.38586030000005],
     [-75.06261651099999, 38.38518499400004],
     [-75.06276263499996, 38.384886453000036],
     [-75.06278974499998, 38.38484618800004],
     [-75.06281355599998, 38.38479300100005],
     [-75.06283069099999, 38.38473313700007],
     [-75.06284284699996, 38.38466829500004],
     [-75.06285139999994, 38.384599851000075],
     [-75.06285746699996, 38.38452891700007],
     [-75.06287397799997, 38.384237436000035],
     [-75.06288002399998, 38.38416648100008],
     [-75.06288854599995, 38.384098006000045],
     [-75.06290066299994, 38.38403312500003],
     [-75.06291774399995, 38.38397320900003],
     [-75.06315327799996, 38.38329631100004],
     [-75.06323869799996, 38.383071812000026],
     [-75.06337788499997, 38.38285488100007],
     [-75.06357065599997, 38.38246053900008],
     [-75.06365579999994, 38.38223576400003],
     [-75.06368720599994, 38.382142663000025]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3264014,
    'MasterKey': 3264014,
    'RandomSort': 2985776.16409383,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.505744,
    'CHLOROPHYLL': 2.62524,
    'TURBIDITY': 0.051783,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 1.820122,
    'GHM': 0.714292,
    'MAX_SLOPE': 4.291832,
    'OUTFLOW_DENSITY': 86378.859375,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 782.4598473481919,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'sinuous',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, sinuous, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 18467,
    'OUTFLOW_DENSITY_RESCALED': 0.0001044389103175128,
    'Shape_Length': 0.007493009648732269},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.07170840747071, 38.37611542403604],
     [-75.07178529399994, 38.37619113100004],
     [-75.07182296399998, 38.37622151000005],
     [-75.07187350999999, 38.376249062000056],
     [-75.07193017999998, 38.376270659000056],
     [-75.07211170699998, 38.376323884000044],
     [-75.07216830899995, 38.37634534800003],
     [-75.07221889499993, 38.376372708000076],
     [-75.07225683399997, 38.37640287200003],
     [-75.07251002799995, 38.37662431800004],
     [-75.07254173899997, 38.37666020700004],
     [-75.07262728499995, 38.37675904900004]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3263901,
    'MasterKey': 3263901,
    'RandomSort': 1558039.81407897,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.489017,
    'CHLOROPHYLL': 2.962768,
    'TURBIDITY': 0.051783,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 3.266431,
    'GHM': 0.583869,
    'MAX_SLOPE': 9.059997,
    'OUTFLOW_DENSITY': 18962.101562,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 783.4104402242039,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'sinuous',
    'slope_label': 'sloping',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'sloping, sinuous, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 18861,
    'OUTFLOW_DENSITY_RESCALED': 2.2926688761514887e-05,
    'Shape_Length': 0.008082806052266082},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.12866460599997, 38.376122602000066],
     [-75.12867162945588, 38.37611542403604]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3263897,
    'MasterKey': 3263897,
    'RandomSort': 2380881.42117463,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.489017,
    'CHLOROPHYLL': 3.025793,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 3.015784,
    'GHM': 0.717243,
    'MAX_SLOPE': 8.405151,
    'OUTFLOW_DENSITY': 18962.101562,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 783.3194660213304,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'sinuous',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, sinuous, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 18467,
    'OUTFLOW_DENSITY_RESCALED': 2.2926688761514887e-05,
    'Shape_Length': 0.00803746897176614},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.14975311399996, 38.377677783000024],
     [-75.14973764499996, 38.37767171000007],
     [-75.14941109199998, 38.37754247300006],
     [-75.14896011299999, 38.377328093000074],
     [-75.14891102399997, 38.377300139000056],
     [-75.14887433699994, 38.37726942200004],
     [-75.14866093899997, 38.37707848300005],
     [-75.14838553999994, 38.37686298600005],
     [-75.14784818899994, 38.376591845000064],
     [-75.14741190599995, 38.376373640000054],
     [-75.14735859799998, 38.376349951000066],
     [-75.14729845299996, 38.37633309700004],
     [-75.14723322099996, 38.37632132900006],
     [-75.14716430999994, 38.37631324200004],
     [-75.14709286399994, 38.37630769000003],
     [-75.14679931099994, 38.37629325000006],
     [-75.14672801299997, 38.37628755000003],
     [-75.14665939299994, 38.37627917100008],
     [-75.14659468199994, 38.376266885000064],
     [-75.14653541299998, 38.37624915400005],
     [-75.14648351999995, 38.376224050000076],
     [-75.14644520399997, 38.37619499200008],
     [-75.14635581746413, 38.37611542403604]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3263898,
    'MasterKey': 3263898,
    'RandomSort': 868735.033150174,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.489017,
    'CHLOROPHYLL': 3.025793,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 3.015784,
    'GHM': 0.717243,
    'MAX_SLOPE': 7.509576,
    'OUTFLOW_DENSITY': 18962.101562,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 783.6540488217547,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'sinuous',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, sinuous, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 18467,
    'OUTFLOW_DENSITY_RESCALED': 2.2926688761514887e-05,
    'Shape_Length': 0.008241943627497658},
   'geometry': {'type': 'LineString',
    'coordinates': [[-75.14525891622483, 38.37611542403604],
     [-75.14528117999998, 38.37615591400004],
     [-75.14530255199998, 38.37621154100003],
     [-75.14535528899995, 38.37638979900004],
     [-75.14537673399997, 38.376445352000076],
     [-75.14540421599997, 38.376494869000055],
     [-75.14543465599996, 38.376531800000066],
     [-75.14563513899998, 38.37673556200008],
     [-75.14567154399998, 38.376766530000054],
     [-75.14572049399999, 38.376794579000034],
     [-75.14617264799995, 38.37700653600007],
     [-75.14639842799994, 38.37709067600008],
     [-75.14707773499998, 38.37732764800006],
     [-75.14714107899994, 38.37734515400007],
     [-75.14720989599994, 38.37735718600004],
     [-75.14728274199996, 38.377365189000045],
     [-75.14735851199998, 38.37737026900004],
     [-75.14743636899993, 38.37737325900008],
     [-75.14759597599993, 38.37737535000008],
     [-75.14800063799998, 38.37737494000004],
     [-75.14815795399994, 38.377379328000075],
     [-75.14823367799994, 38.37738445900004],
     [-75.14830628699997, 38.377392704000044],
     [-75.14837455099996, 38.37740530000008],
     [-75.14843684099998, 38.37742386900004],
     [-75.14849104299998, 38.37745053300006],
     [-75.14852893299997, 38.37748003300004],
     [-75.14874255399997, 38.37767087000003],
     [-75.14901624399994, 38.377889012000026],
     [-75.14955760999999, 38.37816497100005],
     [-75.15000079799995, 38.37838805000007],
     [-75.15005207699994, 38.37841028500003],
     [-75.15010805899993, 38.37842418900004],
     [-75.15016600299998, 38.37843082100005],
     [-75.15022316699998, 38.37843066900007],
     [-75.15027661299996, 38.37842363500005],
     [-75.15032302199995, 38.378409040000065],
     [-75.15035847399997, 38.37838559200003],
     [-75.15037762699995, 38.37835714200003],
     [-75.15038598299998, 38.378323769000076],
     [-75.15038415099997, 38.37828852300004],
     [-75.15037214899996, 38.37825429800006],
     [-75.15035025599997, 38.378223106000064],
     [-75.15017003199995, 38.378016486000035],
     [-75.15013764799994, 38.377979985000024],
     [-75.14988157899995, 38.377752592000036],
     [-75.14984384499996, 38.37772174300005],
     [-75.14979367399997, 38.37769370700005],
     [-75.14975311399996, 38.377677783000024]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3263902,
    'MasterKey': 3263902,
    'RandomSort': 106953.874233128,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.489017,
    'CHLOROPHYLL': 2.928177,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 3.266431,
    'GHM': 0.531868,
    'MAX_SLOPE': 6.635647,
    'OUTFLOW_DENSITY': 18962.101562,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 783.5473991864742,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',
    'sinuosity_label': 'sinuous',
    'slope_label': 'flat',
    'tidal_label': 'moderately tidal',
    'turbid_label': 'clear',
    'wave_label': 'low wave energy',
    'CSU_Descriptor': 'flat, sinuous, high erodibility, warm temperate moist, moderate river discharge, low wave energy, moderately tidal, euhaline-highly oxic-superchilled, clear, moderate chlorophyll',
    'CSU_ID': 18467,
    'OUTFLOW_DENSITY_RESCALED': 2.2926688761514887e-05,
    'Shape_Length': 0.008172688196412222},
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[-75.12509502299997, 38.37969689500005],
      [-75.12456695099996, 38.379517158000056],
      [-75.12433831599998, 38.37943412200008],
      [-75.12394142799997, 38.37923581000007],
      [-75.12389015799994, 38.37920869800007],
      [-75.12384742699999, 38.37917318900003],
      [-75.12381454899997, 38.379124277000074],
      [-75.12379203899997, 38.379065694000076],
      [-75.12377743699994, 38.37900038300006],
      [-75.12376903499995, 38.37893074800007],
      [-75.12376578399994, 38.378858825000066],
      [-75.12376722799996, 38.37878643500005],
      [-75.12377346799997, 38.37871535000005],
      [-75.12378517299999, 38.37864743400007],
      [-75.12380359899998, 38.37858479400006],
      [-75.12383066599995, 38.37852993800004],
      [-75.12386087199997, 38.37849151200004],
      [-75.12406983499994, 38.37828817500008],
      [-75.12410889299997, 38.37825883900007],
      [-75.12416438799994, 38.378232414000024],
      [-75.12422756599994, 38.378213833000075],
      [-75.12429598599994, 38.378200639000056],
      [-75.12436762899995, 38.378190793000044],
      [-75.12451375999996, 38.37817426500004],
      [-75.12458505899997, 38.37816435900004],
      [-75.12465293299994, 38.378151099000036],
      [-75.12471540699994, 38.37813249100003],
      [-75.12477010999999, 38.378106159000026],
      [-75.12480852699997, 38.37807707500008],
      [-75.12502294599994, 38.37788683600007],
      [-75.12505855699999, 38.37785504000004],
      [-75.12508999699998, 38.37781907800007],
      [-75.12514794899994, 38.37774224200007],
      [-75.12517937599995, 38.37770628100003],
      [-75.12521496799997, 38.377674486000046],
      [-75.12542903999997, 38.37748427300005],
      [-75.12546734199998, 38.377455198000064],
      [-75.12552187499995, 38.377428879000036],
      [-75.12558413899995, 38.37741028800008],
      [-75.12565174899999, 38.377397045000066],
      [-75.12572272299997, 38.37738716400003],
      [-75.12586796899996, 38.37737070000003],
      [-75.12593902599997, 38.37736089500004],
      [-75.12600674099997, 38.37734775000007],
      [-75.12606908199996, 38.377329227000075],
      [-75.12612359199994, 38.377302866000036],
      [-75.12616170999996, 38.37727359100006],
      [-75.12636321999997, 38.37707060300005],
      [-75.12639224999998, 38.37703218100006],
      [-75.12641829399996, 38.37697726400006],
      [-75.12643647199997, 38.376914455000076],
      [-75.12644923599998, 38.376846199000056],
      [-75.12645861599998, 38.37677452100007],
      [-75.12647411399996, 38.37662776500008],
      [-75.12648346799995, 38.37655590800006],
      [-75.12649618599994, 38.37648735300007],
      [-75.12651429899995, 38.37642412200006],
      [-75.12654025499995, 38.37636866400004],
      [-75.12656919399996, 38.37632970400006],
      [-75.12676967699997, 38.37612277300008],
      [-75.12677906522092, 38.37611542403604]],
     [[-75.12748530640489, 38.37611542403604],
      [-75.12750471499999, 38.37612916200004],
      [-75.12757953399995, 38.376193425000054],
      [-75.12762028599997, 38.37622232800004],
      [-75.12767401999997, 38.37624818100005],
      [-75.12773442999998, 38.37626725100006],
      [-75.12779982299998, 38.376281111000026],
      [-75.12786883299998, 38.376290967000045],
      [-75.12794035299999, 38.376297703000034],
      [-75.12801344199994, 38.37630191300008],
      [-75.12808728999994, 38.376303937000046],
      [-75.12816112299998, 38.37630387300004],
      [-75.12823415399998, 38.37630157500007],
      [-75.12830551199994, 38.37629663700005],
      [-75.12837417099996, 38.37628837200003],
      [-75.12843887199995, 38.376275759000066],
      [-75.12849803699999, 38.37625738500003],
      [-75.12854967999994, 38.376231379000046],
      [-75.12858758599998, 38.37620131500006],
      [-75.12866460599997, 38.376122602000066]]]}},
  {'type': 'Feature',
   'properties': {'OBJECTID': 3264013,
    'MasterKey': 3264013,
    'RandomSort': 3307597.98670428,
    'MEAN_SIG_WAVEHEIGHT': 0.965667,
    'TIDAL_RANGE': 1.505744,
    'CHLOROPHYLL': 2.583799,
    'TURBIDITY': 0.029,
    'TEMP_MOISTURE': 'Warm Temperate Moist',
    'EMU_PHYSICAL': 'Euhaline-Highly Oxic-Superchilled',
    'REGIONAL_SINUOSITY': 1.820122,
    'GHM': 0.511729,
    'MAX_SLOPE': 2.495855,
    'OUTFLOW_DENSITY': 86378.859375,
    'ERODIBILITY': 'High',
    'Cluster': 6,
    'LENGTH_GEO': 782.8464554419053,
    'chl_label': 'moderate chlorophyll',
    'river_label': 'moderate river discharge',

In [13]:
shoreline_layer_names=[]
for shoreline in shorelines:
    shoreline_layer_name=os.path.basename(shoreline)
    shoreline_layer_names.append(shoreline_layer_name)
shoreline_layer_names

['E_USA_SouthCarolina_NorthCarolina_ref_shoreline.geojson',
 'NE_USA_Delaware_Maine_ref_shoreline.geojson',
 'SE_USA_Louisiana_Georgia_ref_shoreline.geojson',
 'S_USA_Texas_Louisiana_ref_shoreline.geojson',
 'USA_Alaska_ref_shoreline.geojson',
 'W_USA_California_ref_shoreline.geojson',
 'W_USA_Oregon_Washington_ref_shoreline.geojson']

In [10]:
shorelines_folder=os.path.abspath(os.getcwd())+os.sep+"Coastseg"+os.sep+"shorelines"
shorelines=glob.glob(shorelines_folder+os.sep+"*.geojson")
print("shorelines: ",shoreline,"\n")
shoreline_layer_names=[]
for shoreline in shorelines:
    shoreline_layer_name=os.path.basename(shoreline)
    shoreline_layer_names.append(shoreline_layer_name)
shoreline_total_bounds=[]
for shoreline_file in shorelines:
    transects_layer_name=os.path.splitext(os.path.basename(shoreline_file))[0]
    print(transects_layer_name)
    shoreline_gpd=bbox.read_gpd_file(shoreline_file)
    print(shoreline_gpd.total_bounds)
    bounds=shoreline_gpd.total_bounds
    print(bounds,"\n")
    shoreline_total_bounds.append(bounds)

shorelines:  c:\1_USGS\CoastSeg\repos\2_CoastSeg\CoastSeg_fork\Seg2Map\Coastseg\shorelines\W_USA_Oregon_Washington_ref_shoreline.geojson

E_USA_SouthCarolina_NorthCarolina_ref_shoreline
[-81.10107422  32.04533284 -75.04857914  38.46219172]
[-81.10107422  32.04533284 -75.04857914  38.46219172]

NE_USA_Delaware_Maine_ref_shoreline
[-75.78369141  38.37611542 -66.885444    45.62940492]
[-75.78369141  38.37611542 -66.885444    45.62940492]

SE_USA_Louisiana_Georgia_ref_shoreline
[-88.46191406  25.0855989  -80.03099443  32.15701249]
[-88.46191406  25.0855989  -80.03099443  32.15701249]

S_USA_Texas_Louisiana_ref_shoreline
[-97.75944621  25.76031975 -88.39599609  30.54629949]
[-97.75944621  25.76031975 -88.39599609  30.54629949]

USA_Alaska_ref_shoreline
[-172.66113281   52.85586418 -131.52832031   71.38667924]
[-172.66113281   52.85586418 -131.52832031   71.38667924]

W_USA_California_ref_shoreline
[-124.41592646   32.3985158  -117.09123337   42.11452395]
[-124.41592646   32.3985158  -117.09123337   42.11452395]

W_USA_Oregon_Washington_ref_shoreline
[-124.848974     41.8204551  -121.93715578   49.08106236]
[-124.848974     41.8204551  -121.93715578   49.08106236]

In [14]:
shoreline_total_bounds

[array([-81.10107422,  32.04533284, -75.04857914,  38.46219172]),
 array([-75.78369141,  38.37611542, -66.885444  ,  45.62940492]),
 array([-88.46191406,  25.0855989 , -80.03099443,  32.15701249]),
 array([-97.75944621,  25.76031975, -88.39599609,  30.54629949]),
 array([-172.66113281,   52.85586418, -131.52832031,   71.38667924]),
 array([-124.41592646,   32.3985158 , -117.09123337,   42.11452395]),
 array([-124.848974  ,   41.8204551 , -121.93715578,   49.08106236])]

In [15]:
df = pd.DataFrame( shoreline_total_bounds,columns=['minx', 'miny', 'maxx', 'maxy'])
# insert a new column with the names of each geojson file
df.insert(0, 'filename', shoreline_layer_names)
df

,filename,minx,miny,maxx,maxy
0,E_USA_SouthCarolina_NorthCarolina_ref_shorelin...,-81.101074,32.045333,-75.048579,38.462192
1,NE_USA_Delaware_Maine_ref_shoreline.geojson,-75.783691,38.376115,-66.885444,45.629405
2,SE_USA_Louisiana_Georgia_ref_shoreline.geojson,-88.461914,25.085599,-80.030994,32.157012
3,S_USA_Texas_Louisiana_ref_shoreline.geojson,-97.759446,25.760320,-88.395996,30.546299
4,USA_Alaska_ref_shoreline.geojson,-172.661133,52.855864,-131.528320,71.386679
5,W_USA_California_ref_shoreline.geojson,-124.415926,32.398516,-117.091233,42.114524
6,W_USA_Oregon_Washington_ref_shoreline.geojson,-124.848974,41.820455,-121.937156,49.081062

In [16]:
df.to_csv("shorelines_bounding_boxes.csv",index=False)

In [10]:
shorelines_df=pd.read_csv("transects_bounding_boxes.csv")
shorelines_df

                     filename        minx       miny        maxx       maxy
0    CA_USA_transects.geojson -124.406264  32.525625 -117.121819  42.014256
1     E_aus_transects.geojson  149.494188 -37.756402  153.637952 -24.700715
2  Gulf_USA_transects.geojson  -97.379538  25.114007  -81.076218  30.400094
3    SE_USA_transects.geojson  -81.459544  25.665926  -75.456612  36.920862

In [ ]:
shorelines_df=pd.read_csv("shorelines_bounding_boxes.csv")
shorelines_df

:

In [ ]:
|